On explore la donnée.

In [1]:
import pandas as pd
import numpy as np

Pip install odfpy

In [2]:
df = pd.read_excel("C:\\Users\\MCNrm\\Documents\\Telecom_MS\\kit_data\\data-science-project\\raw_data\\hadopi-2020-musique-data.ods", engine="odf")

In [3]:
df.head(5)

,SEXE,QSEXE,RAGE2,RAGE3,XRAGE,AGGLOIFOP2,REG,REG2,REG3,REG13,...,Q60_3,Q60_4,Q60_5,Q61_r1_c1,Q61_r2_c1,Q61_r3_c1,Q61_r4_c1,DISPQUAL,sys_block_set_1,poids
0,Une femme,FEMME,De65aPlus,PlusDe49ans,Femme35ansEtPlus,MoinsDe100000Habitants,UDA7,BUDA4,PROVINCE,LanguedicRoussillonMidiP,...,#NUL!,#NUL!,#NUL!,#NUL!,Entre 1 et 49,#NUL!,#NUL!,Long,"2,3,1",1.006791
1,Une femme,FEMME,De50a64ans1,PlusDe49ans,Femme35ansEtPlus,PlusDe100000Habitants,UDA6,BUDA3,PROVINCE,PaysDeLaLoire1,...,0,0,0,150 et plus,50 et plus,#NUL!,#NUL!,Long,"3,2,1",0.695394
2,Une femme,FEMME,De15a24ans,MoinsDe35ans,FemmeMoinsDe35ans,PlusDe100000Habitants,UDA2,BUDA2,PROVINCE,NordPasDeCalaisPicardie,...,L’offre légale est plus agréable à utiliser,0,0,Entre 50 et 99,#NUL!,Entre 50 et 99,#NUL!,Long,"1,3,2",0.659261
3,Une femme,FEMME,De35a49ans1,De35a49ans2,Femme35ansEtPlus,PlusDe100000Habitants,UDA9,BUDA5,PROVINCE,ProvenceAlpesCoteDAzur,...,#NUL!,#NUL!,#NUL!,Moins de 50,Entre 1 et 49,#NUL!,#NUL!,Long,"1,2,3",1.165641
4,Un homme,HOMME,De50a64ans1,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,0,0,0,Moins de 50,0,#NUL!,Moins de 20,Long,"2,1,3",1.819044

In [4]:
df.tail(5)

,SEXE,QSEXE,RAGE2,RAGE3,XRAGE,AGGLOIFOP2,REG,REG2,REG3,REG13,...,Q60_3,Q60_4,Q60_5,Q61_r1_c1,Q61_r2_c1,Q61_r3_c1,Q61_r4_c1,DISPQUAL,sys_block_set_1,poids
2195,Une femme,FEMME,De35a49ans1,De35a49ans2,Femme35ansEtPlus,MoinsDe100000Habitants,UDA5,BUDA3,PROVINCE,Normandie,...,#NUL!,#NUL!,#NUL!,Moins de 50,Entre 1 et 49,#NUL!,#NUL!,Long,"1,2,3",2.557586
2196,Un homme,HOMME,De35a49ans1,De35a49ans2,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,#NUL!,#NUL!,#NUL!,150 et plus,50 et plus,#NUL!,#NUL!,Long,"2,3,1",2.567871
2197,Une femme,FEMME,De35a49ans1,De35a49ans2,Femme35ansEtPlus,MoinsDe100000Habitants,UDA5,BUDA3,PROVINCE,Normandie,...,#NUL!,#NUL!,#NUL!,#NUL!,#NUL!,#NUL!,#NUL!,Court,NaN,2.557586
2198,Une femme,FEMME,De35a49ans1,De35a49ans2,Femme35ansEtPlus,MoinsDe100000Habitants,UDA6,BUDA3,PROVINCE,PaysDeLaLoire1,...,#NUL!,#NUL!,#NUL!,#NUL!,#NUL!,#NUL!,#NUL!,Court,NaN,2.560643
2199,Une femme,FEMME,De35a49ans1,De35a49ans2,Femme35ansEtPlus,MoinsDe100000Habitants,UDA9,BUDA5,PROVINCE,LanguedicRoussillonMidiP,...,0,L’offre légale gratuite est satisfaisante,0,Entre 50 et 99,#NUL!,#NUL!,#NUL!,Long,"2,3,1",2.654793

In [5]:
df.dtypes

SEXE                object
QSEXE               object
RAGE2               object
RAGE3               object
XRAGE               object
                    ...
Q61_r3_c1           object
Q61_r4_c1           object
DISPQUAL            object
sys_block_set_1     object
poids              float64
Length: 261, dtype: object

In [6]:
df.shape

(2200, 261)

In [7]:
df.columns.tolist()

['SEXE',
 'QSEXE',
 'RAGE2',
 'RAGE3',
 'XRAGE',
 'AGGLOIFOP2',
 'REG',
 'REG2',
 'REG3',
 'REG13',
 'REG13C',
 'PI4',
 'STATUT',
 'PCF4',
 'FOYER',
 'ENF',
 'RS1',
 'QRS1',
 'Q1_1',
 'Q1_2',
 'Q1_3',
 'Q1_4',
 'Q1_5',
 'Q1_6',
 'Q1_7',
 'Q1_8',
 'Q1_9',
 'Q1_10',
 'Q1_11',
 'Q2_r1',
 'Q2_r2',
 'Q2_r3',
 'Q2_r4',
 'Q2_r5',
 'Q2_r6',
 'Q2_r7',
 'Q2_r8',
 'Q2_r9',
 'Q2_r10',
 'Q2_r11',
 'Q3',
 'Q4',
 'Q5_1',
 'Q5_2',
 'Q5_3',
 'Q5_4',
 'Q5_5',
 'Q5_6',
 'Q5_7',
 'Q5_8',
 'Q5_9',
 'Q5_10',
 'Q5_11',
 'Q5_12',
 'Q5_13',
 'Q6_r1',
 'Q6_r2',
 'Q6_r3',
 'Q6_r4',
 'Q6_r5',
 'Q6_r6',
 'Q6_r7',
 'Q7',
 'Q7bis',
 'Q8_1',
 'Q8_2',
 'Q8_3',
 'Q8_4',
 'Q8_5',
 'Q8_6',
 'Q16_1',
 'Q16_2',
 'Q16_3',
 'Q16_4',
 'Q16_5',
 'Q16_6',
 'Q16_7',
 'Q16_8',
 'Q16_9',
 'Q16_10',
 'Q16_11',
 'Q16_12',
 'Q17',
 'Q18_1',
 'Q18_2',
 'Q18_3',
 'Q18_4',
 'Q18_5',
 'Q18_6',
 'Q18_7',
 'Q18_8',
 'Q18_9',
 'Q19_r1',
 'Q19_r2',
 'Q20_r1',
 'Q20_r2',
 'Q20_r3',
 'Q20_r4',
 'Q20_r5',
 'Q21_r1',
 'Q21_r2',
 'Q21_r3',
 'Q21_r4',
 'ALEA',
 'Q22ALEA1',
 'Q22ALEA2',
 'Q23_r1',
 'Q23_r2',
 'Q24_1',
 'Q24_2',
 'Q24_3',
 'Q24_4',
 'Q24_5',
 'Q24_6',
 'Q24_7',
 'Q24_8',
 'Q24_9',
 'Q24_10',
 'Q25_1',
 'Q25_2',
 'Q25_3',
 'Q25_4',
 'Q25_5',
 'Q25_6',
 'Q25_7',
 'Q25_8',
 'Q25_9',
 'Q25_10',
 'Q26_1',
 'Q26_2',
 'Q26_3',
 'Q26_4',
 'Q26_5',
 'Q27',
 'Q28',
 'Q29',
 'Q30_1',
 'Q30_2',
 'Q30_3',
 'Q31_r1',
 'Q31_r2',
 'Q31_r3',
 'Q31_r4',
 'Q31_r5',
 'Q31_r6',
 'Q31_r7',
 'Q31_r8',
 'Q31_r9',
 'Q32_1',
 'Q32_2',
 'Q32_3',
 'Q32_4',
 'Q32_5',
 'Q33_1',
 'Q33_2',
 'Q33_3',
 'Q33_4',
 'Q33_5',
 'Q34_r1',
 'Q34_r2',
 'Q35',
 'Q36_1',
 'Q36_2',
 'Q36_3',
 'Q36_4',
 'Q36_5',
 'Q37ALEA1',
 'Q37ALEA2',
 'Q38_r1_c1',
 'Q38_r2_c1',
 'Q48_1',
 'Q48_2',
 'Q48_3',
 'Q48_4',
 'Q48_5',
 'Q48_6',
 'Q48_7',
 'Q48_8',
 'Q48_9',
 'Q48_10',
 'Q48_11',
 'Q49_1',
 'Q49_2',
 'Q49_3',
 'Q49_4',
 'Q49_5',
 'Q49_6',
 'Q49_7',
 'Q49_8',
 'Q49_9',
 'Q50_1',
 'Q50_2',
 'Q50_3',
 'Q50_4',
 'Q50_5',
 'Q50_6',
 'Q50_7',
 'Q50_8',
 'Q50_9',
 'Q50_10',
 'Q50_11',
 'Q50_12',
 'Q51',
 'Q52_1',
 'Q52_2',
 'Q52_3',
 'Q52_4',
 'Q53_r1_c1',
 'Q53_r2_c1',
 'Q53_r3_c1',
 'Q53_r4_c1',
 'Q53_r5_c1',
 'Q53_r6_c1',
 'Q53_r7_c1',
 'Q53_r8_c1',
 'Q53_r9_c1',
 'Q53_r10_c1',
 'Q54_r1_c1',
 'Q54_r2_c1',
 'Q54_r3_c1',
 'Q54_r4_c1',
 'Q54_r5_c1',
 'Q54_r6_c1',
 'Q54_r7_c1',
 'Q54_r8_c1',
 'Q54_r9_c1',
 'Q55_1',
 'Q55_2',
 'Q55_3',
 'Q55_4',
 'Q55_5',
 'Q55_6',
 'Q55_7',
 'Q55_8',
 'Q56_r1_c1',
 'Q56_r2_c1',
 'Q56_r3_c1',
 'Q56_r4_c1',
 'Q56_r5_c1',
 'Q56_r6_c1',
 'Q57',
 'Q58_1',
 'Q58_2',
 'Q58_3',
 'Q58_4',
 'Q58_5',
 'Q58_6',
 'Q58_7',
 'Q59',
 'Q60_1',
 'Q60_2',
 'Q60_3',
 'Q60_4',
 'Q60_5',
 'Q61_r1_c1',
 'Q61_r2_c1',
 'Q61_r3_c1',
 'Q61_r4_c1',
 'DISPQUAL',
 'sys_block_set_1',
 'poids']

In [8]:
df.count()

SEXE               2200
QSEXE              2200
RAGE2              2200
RAGE3              2200
XRAGE              2200
                   ...
Q61_r3_c1          2200
Q61_r4_c1          2200
DISPQUAL           2200
sys_block_set_1    1986
poids              2200
Length: 261, dtype: int64

In [9]:
with pd.option_context('display.max_rows', None):
    display(df.isnull().sum())

SEXE                 0
QSEXE                0
RAGE2                0
RAGE3                0
XRAGE                0
AGGLOIFOP2           0
REG                  0
REG2                 0
REG3                 0
REG13                0
REG13C               0
PI4                  0
STATUT               0
PCF4                 0
FOYER                0
ENF                  0
RS1                  0
QRS1                 0
Q1_1                 0
Q1_2                 0
Q1_3                 0
Q1_4                 0
Q1_5                 0
Q1_6                 0
Q1_7                 0
Q1_8                 0
Q1_9                 0
Q1_10                0
Q1_11                0
Q2_r1                0
Q2_r2                0
Q2_r3                0
Q2_r4                0
Q2_r5                0
Q2_r6                0
Q2_r7                0
Q2_r8                0
Q2_r9                0
Q2_r10               0
Q2_r11               0
Q3                   0
Q4                   0
Q5_1                 0
Q5_2                 0
Q5_3                 0
Q5_4                 0
Q5_5                 0
Q5_6                 0
Q5_7                 0
Q5_8                 0
Q5_9                 0
Q5_10                0
Q5_11                0
Q5_12                0
Q5_13                0
Q6_r1                0
Q6_r2                0
Q6_r3                0
Q6_r4                0
Q6_r5                0
Q6_r6                0
Q6_r7                0
Q7                   0
Q7bis                0
Q8_1                 0
Q8_2                 0
Q8_3                 0
Q8_4                 0
Q8_5                 0
Q8_6                 0
Q16_1                0
Q16_2                0
Q16_3                0
Q16_4                0
Q16_5                0
Q16_6                0
Q16_7                0
Q16_8                0
Q16_9                0
Q16_10               0
Q16_11               0
Q16_12               0
Q17                  0
Q18_1                0
Q18_2                0
Q18_3                0
Q18_4                0
Q18_5                0
Q18_6                0
Q18_7                0
Q18_8                0
Q18_9                0
Q19_r1               0
Q19_r2               0
Q20_r1               0
Q20_r2               0
Q20_r3               0
Q20_r4               0
Q20_r5               0
Q21_r1               0
Q21_r2               0
Q21_r3               0
Q21_r4               0
ALEA                 0
Q22ALEA1             0
Q22ALEA2             0
Q23_r1               0
Q23_r2               0
Q24_1                0
Q24_2                0
Q24_3                0
Q24_4                0
Q24_5                0
Q24_6                0
Q24_7                0
Q24_8                0
Q24_9                0
Q24_10               0
Q25_1                0
Q25_2                0
Q25_3                0
Q25_4                0
Q25_5                0
Q25_6                0
Q25_7                0
Q25_8                0
Q25_9                0
Q25_10               0
Q26_1                0
Q26_2                0
Q26_3                0
Q26_4                0
Q26_5                0
Q27                  0
Q28                  0
Q29                  0
Q30_1                0
Q30_2                0
Q30_3                0
Q31_r1               0
Q31_r2               0
Q31_r3               0
Q31_r4               0
Q31_r5               0
Q31_r6               0
Q31_r7               0
Q31_r8               0
Q31_r9               0
Q32_1                0
Q32_2                0
Q32_3                0
Q32_4                0
Q32_5                0
Q33_1                0
Q33_2                0
Q33_3                0
Q33_4                0
Q33_5                0
Q34_r1               0
Q34_r2               0
Q35                  0
Q36_1                0
Q36_2                0
Q36_3                0
Q36_4                0
Q36_5                0
Q37ALEA1             0
Q37ALEA2             0
Q38_r1_c1            0
Q38_r2_c1            0
Q48_1                0
Q48_2                0
Q48_3                0
Q48_4                0
Q48_5                0
Q48_6                0
Q48_7                0
Q48_8                0
Q48_9                0
Q48_10               0
Q48_11               0
Q49_1                0
Q49_2                0
Q49_3                0
Q49_4                0
Q49_5                0
Q49_6                0
Q49_7                0
Q49_8                0
Q49_9                0
Q50_1                0
Q50_2                0
Q50_3                0
Q50_4                0
Q50_5                0
Q50_6                0
Q50_7                0
Q50_8                0
Q50_9                0
Q50_10               0
Q50_11               0
Q50_12               0
Q51                  0
Q52_1                0
Q52_2                0
Q52_3                0
Q52_4                0
Q53_r1_c1            0
Q53_r2_c1            0
Q53_r3_c1            0
Q53_r4_c1            0
Q53_r5_c1            0
Q53_r6_c1            0
Q53_r7_c1            0
Q53_r8_c1            0
Q53_r9_c1            0
Q53_r10_c1           0
Q54_r1_c1            0
Q54_r2_c1            0
Q54_r3_c1            0
Q54_r4_c1            0
Q54_r5_c1            0
Q54_r6_c1            0
Q54_r7_c1            0
Q54_r8_c1            0
Q54_r9_c1            0
Q55_1                0
Q55_2                0
Q55_3                0
Q55_4                0
Q55_5                0
Q55_6                0
Q55_7                0
Q55_8                0
Q56_r1_c1            0
Q56_r2_c1            0
Q56_r3_c1            0
Q56_r4_c1            0
Q56_r5_c1            0
Q56_r6_c1            0
Q57                  0
Q58_1                0
Q58_2                0
Q58_3                0
Q58_4                0
Q58_5                0
Q58_6                0
Q58_7                0
Q59                  0
Q60_1                0
Q60_2                0
Q60_3                0
Q60_4                0
Q60_5                0
Q61_r1_c1            0
Q61_r2_c1            0
Q61_r3_c1            0
Q61_r4_c1            0
DISPQUAL             0
sys_block_set_1    214
poids                0
dtype: int64

In [10]:
with pd.option_context('display.max_rows', None):
    display(df.isna().sum())

SEXE                 0
QSEXE                0
RAGE2                0
RAGE3                0
XRAGE                0
AGGLOIFOP2           0
REG                  0
REG2                 0
REG3                 0
REG13                0
REG13C               0
PI4                  0
STATUT               0
PCF4                 0
FOYER                0
ENF                  0
RS1                  0
QRS1                 0
Q1_1                 0
Q1_2                 0
Q1_3                 0
Q1_4                 0
Q1_5                 0
Q1_6                 0
Q1_7                 0
Q1_8                 0
Q1_9                 0
Q1_10                0
Q1_11                0
Q2_r1                0
Q2_r2                0
Q2_r3                0
Q2_r4                0
Q2_r5                0
Q2_r6                0
Q2_r7                0
Q2_r8                0
Q2_r9                0
Q2_r10               0
Q2_r11               0
Q3                   0
Q4                   0
Q5_1                 0
Q5_2                 0
Q5_3                 0
Q5_4                 0
Q5_5                 0
Q5_6                 0
Q5_7                 0
Q5_8                 0
Q5_9                 0
Q5_10                0
Q5_11                0
Q5_12                0
Q5_13                0
Q6_r1                0
Q6_r2                0
Q6_r3                0
Q6_r4                0
Q6_r5                0
Q6_r6                0
Q6_r7                0
Q7                   0
Q7bis                0
Q8_1                 0
Q8_2                 0
Q8_3                 0
Q8_4                 0
Q8_5                 0
Q8_6                 0
Q16_1                0
Q16_2                0
Q16_3                0
Q16_4                0
Q16_5                0
Q16_6                0
Q16_7                0
Q16_8                0
Q16_9                0
Q16_10               0
Q16_11               0
Q16_12               0
Q17                  0
Q18_1                0
Q18_2                0
Q18_3                0
Q18_4                0
Q18_5                0
Q18_6                0
Q18_7                0
Q18_8                0
Q18_9                0
Q19_r1               0
Q19_r2               0
Q20_r1               0
Q20_r2               0
Q20_r3               0
Q20_r4               0
Q20_r5               0
Q21_r1               0
Q21_r2               0
Q21_r3               0
Q21_r4               0
ALEA                 0
Q22ALEA1             0
Q22ALEA2             0
Q23_r1               0
Q23_r2               0
Q24_1                0
Q24_2                0
Q24_3                0
Q24_4                0
Q24_5                0
Q24_6                0
Q24_7                0
Q24_8                0
Q24_9                0
Q24_10               0
Q25_1                0
Q25_2                0
Q25_3                0
Q25_4                0
Q25_5                0
Q25_6                0
Q25_7                0
Q25_8                0
Q25_9                0
Q25_10               0
Q26_1                0
Q26_2                0
Q26_3                0
Q26_4                0
Q26_5                0
Q27                  0
Q28                  0
Q29                  0
Q30_1                0
Q30_2                0
Q30_3                0
Q31_r1               0
Q31_r2               0
Q31_r3               0
Q31_r4               0
Q31_r5               0
Q31_r6               0
Q31_r7               0
Q31_r8               0
Q31_r9               0
Q32_1                0
Q32_2                0
Q32_3                0
Q32_4                0
Q32_5                0
Q33_1                0
Q33_2                0
Q33_3                0
Q33_4                0
Q33_5                0
Q34_r1               0
Q34_r2               0
Q35                  0
Q36_1                0
Q36_2                0
Q36_3                0
Q36_4                0
Q36_5                0
Q37ALEA1             0
Q37ALEA2             0
Q38_r1_c1            0
Q38_r2_c1            0
Q48_1                0
Q48_2                0
Q48_3                0
Q48_4                0
Q48_5                0
Q48_6                0
Q48_7                0
Q48_8                0
Q48_9                0
Q48_10               0
Q48_11               0
Q49_1                0
Q49_2                0
Q49_3                0
Q49_4                0
Q49_5                0
Q49_6                0
Q49_7                0
Q49_8                0
Q49_9                0
Q50_1                0
Q50_2                0
Q50_3                0
Q50_4                0
Q50_5                0
Q50_6                0
Q50_7                0
Q50_8                0
Q50_9                0
Q50_10               0
Q50_11               0
Q50_12               0
Q51                  0
Q52_1                0
Q52_2                0
Q52_3                0
Q52_4                0
Q53_r1_c1            0
Q53_r2_c1            0
Q53_r3_c1            0
Q53_r4_c1            0
Q53_r5_c1            0
Q53_r6_c1            0
Q53_r7_c1            0
Q53_r8_c1            0
Q53_r9_c1            0
Q53_r10_c1           0
Q54_r1_c1            0
Q54_r2_c1            0
Q54_r3_c1            0
Q54_r4_c1            0
Q54_r5_c1            0
Q54_r6_c1            0
Q54_r7_c1            0
Q54_r8_c1            0
Q54_r9_c1            0
Q55_1                0
Q55_2                0
Q55_3                0
Q55_4                0
Q55_5                0
Q55_6                0
Q55_7                0
Q55_8                0
Q56_r1_c1            0
Q56_r2_c1            0
Q56_r3_c1            0
Q56_r4_c1            0
Q56_r5_c1            0
Q56_r6_c1            0
Q57                  0
Q58_1                0
Q58_2                0
Q58_3                0
Q58_4                0
Q58_5                0
Q58_6                0
Q58_7                0
Q59                  0
Q60_1                0
Q60_2                0
Q60_3                0
Q60_4                0
Q60_5                0
Q61_r1_c1            0
Q61_r2_c1            0
Q61_r3_c1            0
Q61_r4_c1            0
DISPQUAL             0
sys_block_set_1    214
poids                0
dtype: int64

Dans le fichier Excel, le nan est marqué comme #NUL!

In [11]:
df = df.replace('#NUL!', np.nan)

C:\Users\MCNrm\AppData\Local\Temp\ipykernel_11808\1331573287.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('#NUL!', np.nan)

In [12]:
with pd.option_context('display.max_rows', None):
    display(df.isna().sum())

SEXE                  0
QSEXE                 0
RAGE2                 0
RAGE3                 0
XRAGE                 0
AGGLOIFOP2            0
REG                   0
REG2                  0
REG3                  0
REG13                 0
REG13C                0
PI4                   0
STATUT                0
PCF4                  0
FOYER                 0
ENF                 399
RS1                   0
QRS1                  0
Q1_1                  0
Q1_2                  0
Q1_3                  0
Q1_4                  0
Q1_5                  0
Q1_6                  0
Q1_7                  0
Q1_8                  0
Q1_9                  0
Q1_10                 0
Q1_11                 0
Q2_r1              1029
Q2_r2              1108
Q2_r3              1202
Q2_r4              1183
Q2_r5              1402
Q2_r6              1673
Q2_r7              1641
Q2_r8              1365
Q2_r9              1771
Q2_r10             2200
Q2_r11             2200
Q3                    0
Q4                 1104
Q5_1                214
Q5_2                214
Q5_3                214
Q5_4                214
Q5_5                214
Q5_6                214
Q5_7                214
Q5_8                214
Q5_9                214
Q5_10               214
Q5_11               214
Q5_12               214
Q5_13               214
Q6_r1               214
Q6_r2               214
Q6_r3               214
Q6_r4               214
Q6_r5               214
Q6_r6               214
Q6_r7               214
Q7                  862
Q7bis               527
Q8_1                533
Q8_2                533
Q8_3                533
Q8_4                533
Q8_5               1224
Q8_6                533
Q16_1               214
Q16_2               214
Q16_3               214
Q16_4               214
Q16_5               214
Q16_6               214
Q16_7               214
Q16_8               214
Q16_9               214
Q16_10              214
Q16_11              214
Q16_12              214
Q17                 703
Q18_1               214
Q18_2               214
Q18_3               214
Q18_4               214
Q18_5               214
Q18_6               214
Q18_7               214
Q18_8               214
Q18_9               214
Q19_r1              214
Q19_r2              214
Q20_r1              214
Q20_r2              214
Q20_r3              214
Q20_r4              214
Q20_r5              214
Q21_r1              214
Q21_r2              214
Q21_r3              214
Q21_r4              214
ALEA                214
Q22ALEA1           1163
Q22ALEA2           1251
Q23_r1              533
Q23_r2              533
Q24_1              1458
Q24_2              1094
Q24_3              1805
Q24_4               214
Q24_5              1174
Q24_6               214
Q24_7               214
Q24_8               214
Q24_9               214
Q24_10              214
Q25_1              1929
Q25_2              1801
Q25_3              2003
Q25_4              1870
Q25_5              1945
Q25_6              1831
Q25_7              1960
Q25_8              2028
Q25_9              1723
Q25_10             2187
Q26_1              1458
Q26_2              1458
Q26_3              1458
Q26_4              1458
Q26_5              1458
Q27                1458
Q28                 214
Q29                 214
Q30_1              1148
Q30_2              1148
Q30_3              1148
Q31_r1              214
Q31_r2              214
Q31_r3              533
Q31_r4              533
Q31_r5              533
Q31_r6              214
Q31_r7             1971
Q31_r8             1971
Q31_r9             1971
Q32_1              1805
Q32_2              1805
Q32_3              1805
Q32_4              1805
Q32_5              1805
Q33_1              1805
Q33_2              1805
Q33_3              1805
Q33_4              1805
Q33_5              1805
Q34_r1             1094
Q34_r2             1094
Q35                1104
Q36_1              1104
Q36_2              1104
Q36_3              1104
Q36_4              1104
Q36_5              1104
Q37ALEA1           1628
Q37ALEA2           1676
Q38_r1_c1          1104
Q38_r2_c1          1104
Q48_1               214
Q48_2               214
Q48_3               214
Q48_4               214
Q48_5               214
Q48_6               214
Q48_7               214
Q48_8               214
Q48_9               214
Q48_10              214
Q48_11              214
Q49_1               214
Q49_2               214
Q49_3               214
Q49_4               214
Q49_5               214
Q49_6               214
Q49_7               214
Q49_8               214
Q49_9               214
Q50_1              1812
Q50_2              1812
Q50_3              1812
Q50_4              1812
Q50_5              1812
Q50_6              1812
Q50_7              1812
Q50_8              1812
Q50_9              1812
Q50_10             1812
Q50_11             1812
Q50_12             1812
Q51                 602
Q52_1               943
Q52_2               943
Q52_3              1945
Q52_4               943
Q53_r1_c1           214
Q53_r2_c1           214
Q53_r3_c1           214
Q53_r4_c1           214
Q53_r5_c1           214
Q53_r6_c1           214
Q53_r7_c1           214
Q53_r8_c1           214
Q53_r9_c1           214
Q53_r10_c1          214
Q54_r1_c1           214
Q54_r2_c1           214
Q54_r3_c1           214
Q54_r4_c1           214
Q54_r5_c1           214
Q54_r6_c1           214
Q54_r7_c1           214
Q54_r8_c1           214
Q54_r9_c1           214
Q55_1              2020
Q55_2              2020
Q55_3              2020
Q55_4              2020
Q55_5              2020
Q55_6              2020
Q55_7              2020
Q55_8              2020
Q56_r1_c1           214
Q56_r2_c1           214
Q56_r3_c1           214
Q56_r4_c1           214
Q56_r5_c1           214
Q56_r6_c1           214
Q57                 533
Q58_1              1126
Q58_2              1126
Q58_3              1126
Q58_4              1126
Q58_5              1126
Q58_6              1126
Q58_7              1126
Q59                1211
Q60_1              1798
Q60_2              1798
Q60_3              1798
Q60_4              1798
Q60_5              1798
Q61_r1_c1          1174
Q61_r2_c1           657
Q61_r3_c1          1812
Q61_r4_c1          1980
DISPQUAL              0
sys_block_set_1     214
poids                 0
dtype: int64

SEXE, QSEXE, RAGE2, RAGE3, XRAGE sont des variables qui concernent le sexe et l'âge de l'individu.

AGGLOIFOP2 nous renseigne sur le nombre d'habitants : plus ou moins de 100 000 .

INTERESSANT

REG3 -> RégionIleDeFrance ou PROVINCE

In [13]:
df["REG3"].value_counts()

REG3
PROVINCE             1759
RegionIleDeFrance     441
Name: count, dtype: int64

REG 13

1	AlsaceChampagneArdenneLo

2	AquitaineLimousinPoitouC

3	AuvergneRhoneAlpes

4	BourgogneFrancheComte

5	Bretagne1

6	CentreValDeLoire

7	Corse1

8	IleDeFrance1

9	LanguedicRoussillonMidiP

10	NordPasDeCalaisPicardie

11	Normandie

12	PaysDeLaLoire1

13	ProvenceAlpesCoteDAzur

In [14]:
df["REG13"].value_counts()

REG13
IleDeFrance1                441
AuvergneRhoneAlpes          271
AlsaceChampagneArdenneLo    220
AquitaineLimousinPoitouC    210
NordPasDeCalaisPicardie     205
LanguedicRoussillonMidiP    178
ProvenceAlpesCoteDAzur      143
PaysDeLaLoire1              139
Bretagne1                   111
Normandie                   102
BourgogneFrancheComte        95
CentreValDeLoire             85
Name: count, dtype: int64

In [15]:
df["REG13C"].value_counts()

REG13C
IleDeFrance2              441
AuvergneRhoneAlpes1       271
AlsaceChampagneArdenn1    220
AquitaineLimousinPoit1    210
NordPasDeCalaisPicard1    205
LanguedicRoussillonMi1    178
PACACorse                 143
PaysDeLaLoire2            139
Bretagne2                 111
Normandie1                102
BourgogneFrancheComte1     95
CentreValDeLoire1          85
Name: count, dtype: int64

In [16]:
df["PI4"].value_counts()

PI4
INACTIFS    918
CSPPLUS     685
CSPMOINS    597
Name: count, dtype: int64

In [17]:
df["STATUT"].value_counts()

STATUT
Vous vivez en couple                           1371
Vous êtes célibataire                           574
Vous êtes un enfant vivant chez vos parents     255
Name: count, dtype: int64

Q2 correspond à un question du type : 

Q2 - Plus précisément, pour chacun des produits ou services culturels suivants, diriez-vous que vous les consommez … ? Une réponse par ligne.  sur Internet … Logiciels

Auxquelles les réponses sont 

- Uniquement de façon légale

- Généralement de façon légale même s’il peut m’arriver de le faire de manière illégale

- Autant de manière légale qu’illégale

- Généralement de façon illégale même s’il peut m’arriver de le faire de manière légale

- Uniquement de manière illégale

Q3 - De manière générale, à quelle fréquence consommez-vous de la musique ou des vidéo clips , quel que soit le support ou le moyen de consommation ?

1	Plusieurs fois par jour

2	Tous les jours ou presque

3	1 à 5 fois par semaine

4	1 à 3 fois par mois

5	Moins souvent

6	Jamais



Si l'individu répond Jamais, le questionnaire s'arrete et les valeurs pour les autres questions sont #NUL!

Q4 - En moyenne, pendant combien de temps consommez-vous de la musique par jour ?  En intégrant les visionnages de clips, et les temps d’écoute pendant que vous faites autre chose.

INTERESSANT

Q5_1 - Quel(s) genre(s) de musique préférez-vous écouter ? Vous pouvez sélectionner plusieurs réponses.

Réponses : 

1	Variété Française

2	Pop / Rock

3	Rap / Hip-Hop

4	Classique

5	Jazz

6	Dance

7	Electronique

8	Métal

9	R&B

10	Soul

11	Reggae

12	Musiques du monde

13	Autres genres

INTERESSANT

Q5_2 - Quel(s) genre(s) de musique préférez-vous écouter ? Vous pouvez sélectionner plusieurs réponses.

Réponses:

1	Variété Française

2	Pop / Rock

3	Rap / Hip-Hop

4	Classique

5	Jazz

6	Dance

7	Electronique

8	Métal

9	R&B

10	Soul

11	Reggae

12	Musiques du monde

13	Autres genres

INTERESSANT

Q5_3 - Quel(s) genre(s) de musique préférez-vous écouter ? Vous pouvez sélectionner plusieurs réponses.

Réponses:

1	Variété Française

2	Pop / Rock

3	Rap / Hip-Hop

4	Classique

5	Jazz

6	Dance

7	Electronique

8	Métal

9	R&B

10	Soul

11	Reggae

12	Musiques du monde

13	Autres genres

Q5 propose 13 choix, donc les choix de Q5_1 a Q5_13 correspondent a chaque catégorie 1 à 1.
Par exemple, si l'individu coche "variété française" et "classique", Q5_1 vaudra "Variété française" et Q5_4 vaudra "Classique".

In [18]:
df["Q5_1"].value_counts()

Q5_1
Variété Française    1217
0                     769
Name: count, dtype: int64

In [19]:
df["Q5_4"].value_counts()

Q5_4
0            1475
Classique     511
Name: count, dtype: int64


<details>
<summary>Les questions du questionnaires qui ne sont pas intéressantes (dérouler)</summary>



**Q6 - A quelle fréquence utilisez-vous les modes d’accès suivants pour écouter / visionner de la musique ?  Une réponse par ligne. Des sites Internet (de streaming, réseaux sociaux, téléchargement, plateformes vidéos…)**


1	Plusieurs fois par jour

2	Tous les jours ou presque

3	1 à 5 fois par semaine

4	1 à 3 fois par mois

5	Moins souvent

6	Jamais

**Q7 - Au cours des 12 derniers mois , à combien de concerts ou de festivals de musique avez-vous assisté ?**

1	5 concerts/festivals ou plus

2	3 ou 4 concerts/festivals

3	1 ou 2 concerts/festivals

4	Aucun

**Q7bis - Vous arrive-t-il d’écouter de la musique sur des stations de radio via Internet ?**

1	Oui

2	Non


**Q16_1** - Quel(s) appareil(s) utilisez-vous pour écouter / visionner de la musique ? Vous pouvez sélectionner plusieurs réponses.

**Q17** - Et quel appareil utilisez-vous le plus souvent pour écouter / visionner de la musique ?

**Q18_1** - Dans votre vie quotidienne, quand écoutez-vous de la musique ? Vous pouvez sélectionner plusieurs réponses.

**Q19** - A quelle fréquence écoutez-vous de la musique… ? Une réponse par ligne. Seul

**Q20** - Pour chacune d’elles, indiquez si cela vous correspond ou non. Une réponse par ligne. Je peux passer des heures à chercher de nouveaux artistes, de nouveaux morceaux inconnus du grand public

**Q21** - Merci d’indiquer votre degré d’accord avec celles-ci.  Une réponse par ligne. Je suis bien informé de la manière dont les artistes sont rémunérés sur ces plateformes

**Q22ALEA1** - Comment définiriez-vous vos goûts musicaux ?

**Q23** - A quelle fréquence faites-vous cela quand vous écoutez de la musique en ligne (sur des plateformes de streaming musical, de partage de vidéos ou des réseaux sociaux, des sites ou applications de radios musicales) ? Une réponse par ligne. Ecouter des albums en entier

**Q24_1** - Quelles sont les sources que vous utilisez pour découvrir des artistes, des titres, des albums que vous ne connaissez pas ? Vous pouvez sélectionner plusieurs réponses.

**Q25_1** - Et quelles sont les 2 principales sources que vous utilisez pour découvrir des artistes, des titres, des albums que vous ne connaissez pas ? Vous pouvez sélectionner 2 réponses maximum.

**Q26_1** - Sur les sites et applications de streaming musical , comment découvrez-vous des artistes, des titres, des albums que vous ne connaissez pas ? Vous pouvez sélectionner plusieurs réponses.

**Q27** - Et le plus souvent , comment découvrez-vous des artistes, des titres, des albums que vous ne connaissez pas , sur les applications de streaming musical ?

**Q28** - Vous arrive-t-il d’utiliser des applications qui permettent de connaître le nom d’un morceau de musique qui est joué autour de vous, comme Shazam par exemple ?

**Q29** - Vous arrive-t-il d’utiliser des convertisseurs (par exemple YouTube to MP3, Clip to MP3, Amerigo, MP3 Juices …) qui permettent de transformer un fichier diffusé en streaming en fichier à télécharger ?

**Q30_1** - Et sur quel(s) appareil(s) utilisez-vous ces convertisseurs ? Vous pouvez sélectionner plusieurs réponses.

**Q31** - Pour chacune d’entre-elles, pouvez-vous nous indiquer si vous êtes tout à fait d’accord, plutôt d’accord, plutôt pas d’accord ou pas du tout d’accord ? Une réponse par ligne. Il est facile de découvrir des nouveautés (artistes, morceaux, genres musicaux) lorsque l’on consomme de la musique en ligne

**Q33_1** - Qui a posté la musique que vous avez écoutée/visionnée sur les réseaux sociaux ? Vous pouvez sélectionner plusieurs réponses.

**Q34** - Et plus particulièrement, à quelle fréquence écoutez-vous / visionnez-vous des vidéos musicales sur des plateformes de partage de vidéos (comme YouTube, Dailymotion) ?  Que ce soit en les regardant ou simplement en écoutant le son de la vidéo sans la regarder.                        Des vidéos clips

**Q35** - Sur YouTube, disposez-vous d’un compte payant ou gratuit avec des identifiants et un mot de passe ?

**Q36_1** - Etes-vous abonné aux contenus suivants sur YouTube ? Vous pouvez sélectionner plusieurs réponses.

**Q37ALEA1** - Quelle déclaration décrit le mieux votre écoute sur YouTube ?

**Q38** - En proportion, quand vous consommez de la musique sur YouTube , quelle est la part de vidéos/clips que vous écoutez en regardant l’écran et la part de ceux que vous écoutez simplement, sans regarder l’écran ? Saisissez vos réponses dans les espaces dédiés.           Vous écoutez de la musique sans regarder la vidéo à l’écran: /____/ % des morceaux que vous écoutez sur YouTube

**Q48_1** - Selon vous, quels sont les principaux avantages à souscrire à un abonnement de streaming musical (Deezer, Spotify, Apple Music…) ? Vous pouvez sélectionner plusieurs réponses.

**Q49_1** - Selon vous, quels sont les principaux inconvénients à souscrire à un abonnement de streaming musical (Deezer, Spotify, Apple Music…) ? Vous pouvez sélectionner plusieurs réponses.

**Q50_1** - Parmi les raisons suivantes, lesquelles vous ont incité à vous abonner à cette offre de streaming plutôt qu’à une autre ? Vous pouvez sélectionner plusieurs réponses.

**Q51** - Avez-vous l’intention de vous abonner à une offre payante de streaming musical (Deezer, Spotify, Apple Music…) dans les prochains mois ?

**Q52_1** - Pour quelles raisons ne souhaitez-vous pas vous abonner à une offre payante de streaming musical ? Vous pouvez sélectionner plusieurs réponses.

**Q53** - Selon l’image que vous en avez, quelle note de 0 à 10 donneriez-vous aux abonnements payants aux services de streaming musical (Spotify, Deezer, Soundcloud…), sur les dimensions suivantes ? Saisissez vos réponses dans les cadres ci-dessous. La qualité des contenus proposés

**Q54** - Selon l’image que vous en avez, quelle note de 0 à 10 donneriez-vous aux offres gratuites de streaming musical (comptes gratuits sur les plateformes de streaming [comme Spotify ou Deezer] ou de vidéos [YouTube]), sur les dimensions suivantes ?         La qualité des contenus proposés 


**Q55_1** - Indiquez quels moyens vous utilisez pour consommer ces produits illégalement . Vous pouvez sélectionner plusieurs réponses.

**Q56** - Selon l’image que vous en avez, quelle note de 0 à 10 donneriez-vous aux moyens illégaux de consommer de la musique en ligne , sur les dimensions suivantes ? Saisissez vos réponses dans les cadres ci-dessous. Une réponse par ligne. La qualité des contenus proposés

**Q57** - Concernant votre consommation de musique, diriez-vous qu’aujourd’hui ... ?

**Q58_1** - Pour quelle(s) raison(s) consommez-vous de la musique illégalement ? Vous pouvez sélectionner plusieurs réponses.

**Q59** - Par le passé, vous est-il déjà arrivé de consommer, sur Internet, de la musique de manière illégale ?

**Q60_1** - Pour quelles raisons avez-vous arrêté de consommer de la musique de manière illégale sur Internet ? Vous pouvez sélectionner plusieurs réponses.

**Q61** - Au cours des 12 derniers mois , quel budget estimez-vous avoir consacré à la musique ? Merci d'indiquer un montant par type de dépense :  Par exemple, pour un abonnement à une offre musicale de 9,99 euros par mois, vous avez consacré 119,88 euros au cours des 12 derniers mois (9,99 * 12).                             En places de concerts / festivals 




Du texte en **gras** ou du code.

</details>

Sys_block_set_1 : Randomized Block Numbers

la variable poids correspond très probablement au poids statistique de chaque répondant. Une personne qui écoute en streaming devrait avoir plus de poids qu'une personne n'écoutant pas en streaming.

FINALEMENT

On retient REG13 et les réponses aux questions Q5.

In [31]:
q5 = []
for col in df.columns:
    if col.find("Q5_") >=0 :
        q5.append(col)

In [22]:
q5

['Q5_1',
 'Q5_2',
 'Q5_3',
 'Q5_4',
 'Q5_5',
 'Q5_6',
 'Q5_7',
 'Q5_8',
 'Q5_9',
 'Q5_10',
 'Q5_11',
 'Q5_12',
 'Q5_13']

In [23]:
df[q5]

,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q5_9,Q5_10,Q5_11,Q5_12,Q5_13
0,Variété Française,0,0,0,Jazz,0,0,0,0,Soul,0,0,0
1,0,Pop / Rock,0,0,Jazz,0,0,0,0,0,0,Musiques du monde,0
2,Variété Française,Pop / Rock,Rap / Hip-Hop,0,0,0,0,0,R&B,0,0,0,0
3,Variété Française,0,0,Classique,0,0,0,0,0,0,0,0,0
4,Variété Française,0,0,0,Jazz,0,0,0,0,0,0,Musiques du monde,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,Variété Française,Pop / Rock,Rap / Hip-Hop,0,0,0,0,0,R&B,0,0,0,0
2196,0,Pop / Rock,0,0,0,0,0,0,0,0,0,0,0
2197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2199,Variété Française,0,Rap / Hip-Hop,0,0,Dance,0,0,R&B,0,0,0,0

In [ ]:
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (6, 261)

In [32]:
col_raw = q5 + ["REG13"]

In [36]:
print(col_raw)

['Q5_1', 'Q5_2', 'Q5_3', 'Q5_4', 'Q5_5', 'Q5_6', 'Q5_7', 'Q5_8', 'Q5_9', 'Q5_10', 'Q5_11', 'Q5_12', 'Q5_13', 'REG13']

In [37]:
df_raw = df[col_raw]

In [38]:
df_raw

,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q5_9,Q5_10,Q5_11,Q5_12,Q5_13,REG13
0,Variété Française,0,0,0,Jazz,0,0,0,0,Soul,0,0,0,LanguedicRoussillonMidiP
1,0,Pop / Rock,0,0,Jazz,0,0,0,0,0,0,Musiques du monde,0,PaysDeLaLoire1
2,Variété Française,Pop / Rock,Rap / Hip-Hop,0,0,0,0,0,R&B,0,0,0,0,NordPasDeCalaisPicardie
3,Variété Française,0,0,Classique,0,0,0,0,0,0,0,0,0,ProvenceAlpesCoteDAzur
4,Variété Française,0,0,0,Jazz,0,0,0,0,0,0,Musiques du monde,0,AuvergneRhoneAlpes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,Variété Française,Pop / Rock,Rap / Hip-Hop,0,0,0,0,0,R&B,0,0,0,0,Normandie
2196,0,Pop / Rock,0,0,0,0,0,0,0,0,0,0,0,AuvergneRhoneAlpes
2197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normandie
2198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PaysDeLaLoire1
2199,Variété Française,0,Rap / Hip-Hop,0,0,Dance,0,0,R&B,0,0,0,0,LanguedicRoussillonMidiP

NaN correspond à des personnes qui n'ont pas du tout répondu, tandis que 0 signifie qu'il n'a pas coché la réponse.
On conserve donc les 0 mais on supprime les lignes avec NaN.

In [39]:
duplicate_rows_df = df_raw[df_raw.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (840, 14)