In [1]:
#mettre dans requirements.txt
import pandas as pd
import os 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
filepath = "../Dataset/dataset_musique_region.csv"
#df = pd.read_excel(filepath)
df = pd.read_csv(filepath)

In [3]:
df

,variete_francaise,pop_rock,rap_hip_hop,classique,jazz,dance,electronique,metal,rnb,soul,reggae,musiques_du_monde,autres_genres,region
0,1,0,0,0,1,0,0,0,0,1,0,0,0,Occitanie
1,0,1,0,0,1,0,0,0,0,0,0,1,0,Pays de la Loire
2,1,1,1,0,0,0,0,0,1,0,0,0,0,Hauts-de-France
3,1,0,0,1,0,0,0,0,0,0,0,0,0,Provence-Alpes-Côte d'Azur
4,1,0,0,0,1,0,0,0,0,0,0,1,0,Auvergne-Rhône-Alpes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,0,1,0,0,0,0,0,0,0,0,0,0,0,Île-de-France
1982,1,1,1,1,0,0,0,0,0,1,0,0,0,Île-de-France
1983,1,1,1,0,0,0,0,0,1,0,0,0,0,Normandie
1984,0,1,0,0,0,0,0,0,0,0,0,0,0,Auvergne-Rhône-Alpes
1985,1,0,1,0,0,1,0,0,1,0,0,0,0,Occitanie

# Regions trop petites

On veut trouver les régions trop petites.

In [4]:
df["region"].value_counts()

region
Île-de-France                 404
Auvergne-Rhône-Alpes          237
Grand Est                     200
Nouvelle-Aquitaine            194
Hauts-de-France               188
Occitanie                     161
Provence-Alpes-Côte d'Azur    129
Pays de la Loire              125
Bretagne                       97
Normandie                      89
Bourgogne-Franche-Comté        84
Centre-Val de Loire            78
Name: count, dtype: int64

In [5]:
import plotly.express as px

In [6]:
df_counts = df["region"].value_counts().reset_index(name="count")

In [7]:
px.bar(df_counts, x="region", y="count", title="Nombre d'occurences par région")

On décide de regrouper : 

Centre-Val de Loire / Pays de la Loire / Bourgogne-Franche-Comté -> groupement CENTRE

Normandie / Bretagne / Hauts-de-France -> groupement NORD-OUEST

Provence-Alpes-Côte d'Azur / Occitanie -> groupement SUD

In [8]:
def groupement(region):
    if region == "Centre-Val de Loire" or region == "Pays de la Loire" or region == "Bourgogne-Franche-Comté":
        return "CENTRE"
    elif region == "Normandie" or region == "Bretagne" or region == "Hauts-de-France":
        return "NORD-OUEST"
    elif region == "Provence-Alpes-Côte d'Azur" or region == "Occitanie":
        return "SUD"
    else:
        return region

In [9]:
df["region_group"] = df["region"].apply(groupement)

In [10]:
df

,variete_francaise,pop_rock,rap_hip_hop,classique,jazz,dance,electronique,metal,rnb,soul,reggae,musiques_du_monde,autres_genres,region,region_group
0,1,0,0,0,1,0,0,0,0,1,0,0,0,Occitanie,SUD
1,0,1,0,0,1,0,0,0,0,0,0,1,0,Pays de la Loire,CENTRE
2,1,1,1,0,0,0,0,0,1,0,0,0,0,Hauts-de-France,NORD-OUEST
3,1,0,0,1,0,0,0,0,0,0,0,0,0,Provence-Alpes-Côte d'Azur,SUD
4,1,0,0,0,1,0,0,0,0,0,0,1,0,Auvergne-Rhône-Alpes,Auvergne-Rhône-Alpes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,0,1,0,0,0,0,0,0,0,0,0,0,0,Île-de-France,Île-de-France
1982,1,1,1,1,0,0,0,0,0,1,0,0,0,Île-de-France,Île-de-France
1983,1,1,1,0,0,0,0,0,1,0,0,0,0,Normandie,NORD-OUEST
1984,0,1,0,0,0,0,0,0,0,0,0,0,0,Auvergne-Rhône-Alpes,Auvergne-Rhône-Alpes
1985,1,0,1,0,0,1,0,0,1,0,0,0,0,Occitanie,SUD

In [11]:
df_counts_gr_reg = df["region_group"].value_counts().reset_index(name="count")

In [12]:
px.bar(df_counts_gr_reg, x="region_group", y="count", title="Nombre d'occurences par région")

In [13]:
df["region_group"].value_counts()

region_group
Île-de-France           404
NORD-OUEST              374
SUD                     290
CENTRE                  287
Auvergne-Rhône-Alpes    237
Grand Est               200
Nouvelle-Aquitaine      194
Name: count, dtype: int64

Groupement plus restrictif NORD SUD EST OUEST IDF

In [ ]:
def groupement_restrictif(region):
    if region == "Centre-Val de Loire" or region == "Auvergne-Rhône-Alpes":
        return "CENTRE"
    elif region == "Normandie" or region == "Hauts-de-France":
        return "NORD"
    elif region == "Provence-Alpes-Côte d'Azur" or region == "Occitanie":
        return "SUD"
    elif region == "Bretagne" or region == "Pays de la Loire" or region == "Nouvelle-Aquitaine":
        return "OUEST"
    elif region == "Grand Est" or region == "Bourgogne-Franche-Comté":
        return "EST"
    else:
        return region

# Autres niveaux de région

La colonne Ile de France / Province existe déjà dans le dataset original

# Fréquence de chaque style

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1986 entries, 0 to 1985
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   variete_francaise  1986 non-null   int64
 1   pop_rock           1986 non-null   int64
 2   rap_hip_hop        1986 non-null   int64
 3   classique          1986 non-null   int64
 4   jazz               1986 non-null   int64
 5   dance              1986 non-null   int64
 6   electronique       1986 non-null   int64
 7   metal              1986 non-null   int64
 8   rnb                1986 non-null   int64
 9   soul               1986 non-null   int64
 10  reggae             1986 non-null   int64
 11  musiques_du_monde  1986 non-null   int64
 12  autres_genres      1986 non-null   int64
 13  region             1986 non-null   object
 14  region_group       1986 non-null   object
dtypes: int64(13), object(2)
memory usage: 232.9+ KB

In [15]:
df["variete_francaise"].value_counts(normalize=True)

variete_francaise
1    0.61279
0    0.38721
Name: proportion, dtype: float64

In [16]:
type(df["variete_francaise"].dtype)

numpy.dtypes.Int64DType

In [24]:
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import math
from IPython.display import display

# Récupérer les colonnes de type int64
columns = [column for column in df.columns if df[column].dtype == "int64"]

# Définir la grille
n_cols = 2
n_rows = math.ceil(len(columns) / n_cols)

fig = make_subplots(
    rows=n_rows,
    cols=n_cols,
    specs=[[{"type": "domain"} for _ in range(n_cols)]
           for _ in range(n_rows)],
    subplot_titles=[f"Répartition de {column}" for column in columns]
)

for i, column in enumerate(columns):
    df_prop = (
        df[column]
        .value_counts(normalize=True)
        .reset_index(name="proportion")
        .sort_values(by=column, ascending=True)
        .replace({1: "selectionné", 0: "non-selectionné"})
    )

    fig.add_trace(
        go.Pie(
            labels=df_prop[column],
            values=df_prop["proportion"],
            textinfo="percent+label",
            name=column
        ),
        row=i // n_cols + 1,
        col=i % n_cols + 1
    )

fig.update_layout(
    title_text="Répartition des variables numériques",
    height=400 * n_rows,
    width=1000,
    showlegend=False
)

fig.show()

# Nombre de styles écoutés

In [19]:
df["variete_francaise"] + df["musiques_du_monde"]

0       1
1       1
2       1
3       1
4       2
       ..
1981    0
1982    1
1983    1
1984    0
1985    1
Length: 1986, dtype: int64

In [20]:
df["total_genres"] = df.iloc[:,0:13].sum(axis=1)

In [21]:
df["total_genres"].value_counts()

total_genres
3     418
2     412
1     347
4     290
5     218
6     127
7      89
8      33
9      23
10     11
12      9
11      8
13      1
Name: count, dtype: int64